-- MySQL Script generated by MySQL Workbench
-- Sat May 17 21:55:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET utf8 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(19,4) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `descricao` TEXT NULL,
  `img_url` VARCHAR(250) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `renda` DECIMAL(19,4) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `criacao` DATE NOT NULL,
  `prox_interacao` DATE NULL,
  `descricao` TEXT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_cliente_produto_idx` (`produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_produto`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `crm`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`interacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`interacao` (
  `idinteracao` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `data` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idinteracao`),
  INDEX `fk_interacao_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_interacao_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_interacao_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `crm`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interacao_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `crm`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
